#!/bin/bash

# تقرير لاستهلاك الذاكرة والمعالج
MEMORY_USAGE=$(free -h)
CPU_USAGE=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1 "%"}')

# حفظ التقرير في ملف
REPORT="/tmp/system_report_$(date +'%Y%m%d%H%M').txt"
echo "Report Generated on $(date)" > $REPORT
echo "=========================" >> $REPORT
echo "Memory Usage:" >> $REPORT
echo "$MEMORY_USAGE" >> $REPORT
echo "=========================" >> $REPORT
echo "CPU Usage:" >> $REPORT
echo "$CPU_USAGE" >> $REPORT


MAIL_TO="your-email@example.com"
MAIL_SUBJECT="System Performance Report"
mail -s "$MAIL_SUBJECT" $MAIL_TO < $REPORT


rm $REPORT
